use utoipa::OpenApi;

use crate::{
    core::health::{self, HealthResponse},
    modules::{
        auth::{
            dto::{
                AuthRole, AuthStatusResponse, AuthenticatedUserResponse, CreateUserRequest,
                CredentialsRequest, RolePermissionsResponse, SetupRequest, UserResponse,
            },
            handlers as auth_handlers,
        },
        authors::{
            dto::{AuthorAvatarResponse, AuthorDetailResponse, AuthorResponse},
            handlers as author_handlers,
        },
        libraries::{
            dto::{
                CreateLibraryRequest, DeleteLibraryResponse, LibraryPreviewJobResponse,
                LibraryPreviewStatusResponse, LibraryResponse, MediaType,
                PreviewGenerationTaskResponse, UpdateLibraryPreviewConfigRequest,
                UpdateLibraryRequest,
            },
            handlers as library_handlers,
        },
        manga::{
            dto::{
                MangaChapterResponse, MangaDetailResponse, MangaPageResponse, MangaReaderResponse,
                MangaSeriesResponse,
            },
            handlers as manga_handlers,
        },
        media::{
            dto::{MediaFileResponse, MediaItemResponse},
            handlers as media_handlers,
        },
        photos::{
            dto::{
                DeletePhotoResponse, PhotoAssetResponse, PhotoFolderContentsResponse,
                PhotoFolderResponse,
            },
            handlers as photo_handlers,
        },
        preferences::{
            dto::{PreferencesResponse, UpdatePreferencesRequest},
            handlers as preference_handlers,
        },
        recycle_bin::{
            dto::{
                PurgeRecycleBinItemResponse, RecycleBinItemResponse, RestoreRecycleBinItemResponse,
            },
            handlers as recycle_bin_handlers,
        },
        scanner::{
            dto::{CreateScanTaskRequest, ScanTaskResponse, ScanTaskStatus},
            handlers as scanner_handlers,
        },
        tags::{
            dto::{
                CreateTagRequest, ReplaceResourceTagsRequest, TagResourceResponse, TagResponse,
                UpdateTagRequest,
            },
            handlers as tag_handlers,
        },
        tasks::{
            dto::{DeleteTasksResponse, TaskResponse, TaskStatus, TaskSummaryResponse},
            handlers as task_handlers,
        },
        videos::{
            dto::{
                UpdateVideoPlaybackRequest, VideoAssetResponse, VideoCatalogResponse,
                VideoCollectionResponse, VideoCoverJobResponse, VideoDetailResponse,
                VideoPlaybackResponse,
            },
            handlers as video_handlers,
        },
        webdav::{
            dto::{CreateWebdavConnectionRequest, WebdavConnectionResponse},
            handlers as webdav_handlers,
        },
    },
};

#[derive(OpenApi)]
#[openapi(
    paths(
        health::health,
        auth_handlers::status,
        auth_handlers::setup,
        auth_handlers::login,
        auth_handlers::logout,
        auth_handlers::me,
        auth_handlers::list_users,
        auth_handlers::create_user,
        auth_handlers::list_role_permissions,
        library_handlers::list_libraries,
        library_handlers::list_library_covers,
        library_handlers::create_library,
        library_handlers::get_library,
        library_handlers::update_library,
        library_handlers::delete_library,
        library_handlers::update_library_preview_config,
        library_handlers::generate_library_preview_assets,
        library_handlers::get_library_preview_generation_task,
        library_handlers::delete_library_preview_assets,
        webdav_handlers::list,
        webdav_handlers::create,
        media_handlers::list_media_items,
        media_handlers::list_media_files,
        media_handlers::get_media_file_content,
        video_handlers::list_videos,
        video_handlers::list_video_catalog,
        video_handlers::get_video,
        video_handlers::update_playback,
        video_handlers::delete_covers,
        video_handlers::get_poster,
        manga_handlers::list_series,
        manga_handlers::get_series,
        manga_handlers::get_reader,
        author_handlers::list_authors,
        author_handlers::get_author,
        photo_handlers::list_photos,
        photo_handlers::list_folder_contents,
        photo_handlers::delete_photo,
        recycle_bin_handlers::list_recycle_bin,
        recycle_bin_handlers::restore_item,
        recycle_bin_handlers::purge_item,
        preference_handlers::get_preferences,
        preference_handlers::update_preferences,
        scanner_handlers::list_scan_tasks,
        scanner_handlers::start_scan,
        task_handlers::list_tasks,
        task_handlers::task_summary,
        task_handlers::delete_task,
        task_handlers::clear_completed_tasks,
        task_handlers::pause_task,
        task_handlers::resume_task,
        task_handlers::cancel_task,
        task_handlers::retry_task,
        tag_handlers::list_tags,
        tag_handlers::create_tag,
        tag_handlers::update_tag,
        tag_handlers::delete_tag,
        tag_handlers::clear_tags,
        tag_handlers::list_resource_tags,
        tag_handlers::replace_resource_tags,
        tag_handlers::list_tag_resources,
    ),
    components(schemas(
        HealthResponse,
        AuthRole,
        CredentialsRequest,
        SetupRequest,
        CreateUserRequest,
        AuthStatusResponse,
        UserResponse,
        AuthenticatedUserResponse,
        RolePermissionsResponse,
        MediaType,
        CreateLibraryRequest,
        UpdateLibraryRequest,
        UpdateLibraryPreviewConfigRequest,
        DeleteLibraryResponse,
        LibraryResponse,
        LibraryPreviewStatusResponse,
        LibraryPreviewJobResponse,
        PreviewGenerationTaskResponse,
        CreateWebdavConnectionRequest,
        WebdavConnectionResponse,
        MediaItemResponse,
        MediaFileResponse,
        VideoAssetResponse,
        VideoCatalogResponse,
        VideoDetailResponse,
        VideoCollectionResponse,
        UpdateVideoPlaybackRequest,
        VideoPlaybackResponse,
        VideoCoverJobResponse,
        MangaSeriesResponse,
        MangaChapterResponse,
        MangaDetailResponse,
        MangaPageResponse,
        MangaReaderResponse,
        AuthorResponse,
        AuthorAvatarResponse,
        AuthorDetailResponse,
        PhotoAssetResponse,
        PhotoFolderResponse,
        PhotoFolderContentsResponse,
        DeletePhotoResponse,
        RecycleBinItemResponse,
        RestoreRecycleBinItemResponse,
        PurgeRecycleBinItemResponse,
        PreferencesResponse,
        UpdatePreferencesRequest,
        ScanTaskStatus,
        CreateScanTaskRequest,
        ScanTaskResponse,
        TaskStatus,
        TaskResponse,
        DeleteTasksResponse,
        TaskSummaryResponse,
        TagResponse,
        CreateTagRequest,
        UpdateTagRequest,
        ReplaceResourceTagsRequest
        ,TagResourceResponse
    )),
    tags(
        (name = "libraries", description = "Media library source directories"),
        (name = "auth", description = "Authentication, users, roles and permissions"),
        (name = "media", description = "Scanned media items and files"),
        (name = "videos", description = "Reusable video assets for video, movie and series catalogues"),
        (name = "manga", description = "Image manga series, chapters and reader pages"),
        (name = "authors", description = "Shared media author library"),
        (name = "photos", description = "Photo gallery assets"),
        (name = "recycle-bin", description = "Soft-deleted media resources"),
        (name = "preferences", description = "Application preferences"),
        (name = "scanner", description = "Filesystem scan tasks"),
        (name = "webdav", description = "Remote WebDAV connections"),
        (name = "tasks", description = "Unified application task feed")
        ,(name = "tags", description = "Global tag library and media resource associations")
    )
)]
pub struct ApiDoc;
