import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "./components/Head";
import SideBar from "./components/SideBar";
import { ThemeProvider } from "./components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitScript = `
(() => {
  const key = "mengnex.theme";
  const stored = window.localStorage.getItem(key);
  const mode = stored === "light" || stored === "dark" || stored === "system" ? stored : "system";
  const resolved = mode === "system"
    ? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light")
    : mode;
  document.documentElement.classList.toggle("dark", resolved === "dark");
  document.documentElement.dataset.theme = resolved;
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="h-full overflow-hidden">
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
        <ThemeProvider>
          <div className="flex h-dvh min-h-0 flex-col overflow-hidden" style={{ background: "var(--theme-bg-app)" }}>
            <Head />
            <div className="m-1 min-h-0 flex-1 rounded-lg overflow-hidden">
              <div className="flex h-full min-h-0 overflow-hidden rounded-lg">
                <SideBar />
                <main
                  className="content-body relative my-2 mr-2 min-h-0 min-w-0 flex-1 overflow-auto rounded-lg p-4 shadow-inner backdrop-blur-xl"
                >
                  {children}
                </main>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
