import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "./components/Head";
import SideBar from "./components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-full overflow-hidden">
        <div className="flex h-dvh min-h-0 flex-col overflow-hidden bg-gray-200">
          <Head />
          <div className="m-1 min-h-0 flex-1 rounded-lg overflow-hidden">
            <div className="flex h-full min-h-0 overflow-hidden rounded-lg">
              <SideBar />
              <main className="content-body relative my-2 mr-2 min-h-0 min-w-0 flex-1 overflow-auto rounded-lg bg-white/50 p-4 shadow-inner">
                {children}
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
