import type { ChatMessage, ChatTool } from "./llm.js";
import type { ProviderSettings } from "./providers.js";
export type ResolvedProviderSettings = ProviderSettings & { apiKey: string };

export type LlmFailureKind = "configuration" | "authentication" | "rate_limit" | "timeout" | "network" | "protocol" | "server" | "unknown";
export class LlmAdapterError extends Error { constructor(message: string, readonly kind: LlmFailureKind, readonly retryable: boolean, options?: ErrorOptions) { super(message, options); this.name = "LlmAdapterError"; } }
export type LlmUsage = { promptTokens?: number; completionTokens?: number; totalTokens?: number };
export type LlmCompletion = { content: string; reasoning: string; tool_calls: Array<{ id: string; type: "function"; function: { name: string; arguments: string } }>; model: string; usage?: LlmUsage };
export type LlmDelta = { content?: string; reasoning?: string; toolCall?: { index: number; id?: string; name?: string; arguments?: string }; usage?: LlmUsage; model?: string };
export type LlmAdapter = { id: string; name: string; models: (provider: ResolvedProviderSettings, options?: { signal?: AbortSignal }) => Promise<Array<{ id: string; name: string; contextWindow?: number }>>; complete: (provider: ResolvedProviderSettings, messages: ChatMessage[], tools: ChatTool[], options: { signal?: AbortSignal }) => Promise<LlmCompletion>; stream?: (provider: ResolvedProviderSettings, messages: ChatMessage[], tools: ChatTool[], options: { signal?: AbortSignal }) => AsyncIterable<LlmDelta>; testConnection: (provider: ResolvedProviderSettings, options: { signal?: AbortSignal }) => Promise<{ ok: true; latencyMs: number; model: string }> };

export function classifyLlmFailure(error: unknown): LlmAdapterError { if (error instanceof LlmAdapterError) return error; if (error instanceof DOMException && error.name === "AbortError") return new LlmAdapterError("model request timed out", "timeout", true, { cause: error }); if (error instanceof TypeError) return new LlmAdapterError(error.message, "network", true, { cause: error }); return new LlmAdapterError(error instanceof Error ? error.message : "model request failed", "unknown", false, { cause: error as Error }); }

export function createOpenAiCompatibleAdapter(fetchImpl: typeof fetch = fetch): LlmAdapter {
  const request = async (provider: ResolvedProviderSettings, path: string, body: Record<string, unknown> | undefined, signal?: AbortSignal) => { let response: Response; try { response = await fetchImpl(`${provider.baseUrl}${path}`, { method: body ? "POST" : "GET", headers: { "Content-Type": "application/json", Authorization: `Bearer ${provider.apiKey}` }, ...(body ? { body: JSON.stringify(body) } : {}), signal }); } catch (error) { throw classifyLlmFailure(error); } const payload = await response.json().catch(() => ({})) as Record<string, any>; if (!response.ok) { const status = response.status; const kind: LlmFailureKind = status === 401 || status === 403 ? "authentication" : status === 429 ? "rate_limit" : status >= 500 ? "server" : "protocol"; throw new LlmAdapterError(payload.error?.message ?? `model provider request failed (${status})`, kind, kind === "rate_limit" || kind === "server"); } return payload; };
  return { id: "openai_compatible", name: "OpenAI Compatible", async models(provider) { const payload = await request(provider, "/models", undefined); return Array.isArray(payload.data) ? payload.data.filter((item: any) => typeof item?.id === "string").map((item: any) => ({ id: item.id, name: item.id })) : [{ id: provider.model, name: provider.model }]; }, async complete(provider, messages, tools, options) { const payload = await request(provider, "/chat/completions", { model: provider.model, messages, temperature: 0.4, ...(tools.length ? { tools, tool_choice: "auto" } : {}) }, options.signal); return completionFromPayload(payload, provider.model); }, async *stream(provider, messages, tools, options) { let response: Response; try { response = await fetchImpl(`${provider.baseUrl}/chat/completions`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${provider.apiKey}` }, body: JSON.stringify({ model: provider.model, messages, temperature: 0.4, stream: true, stream_options: { include_usage: true }, ...(tools.length ? { tools, tool_choice: "auto" } : {}) }), signal: options.signal }); } catch (error) { throw classifyLlmFailure(error); } if (!response.ok || !response.body) { const payload = await response.json().catch(() => ({})) as Record<string, any>; const message = payload.error?.message ?? payload.message ?? `model provider streaming request failed (${response.status})`; const kind: LlmFailureKind = response.status === 400 ? "protocol" : response.status === 401 || response.status === 403 ? "authentication" : response.status === 429 ? "rate_limit" : response.status >= 500 ? "server" : "protocol"; throw new LlmAdapterError(message, kind, response.status === 429 || response.status >= 500); } yield* parseSse(response.body); }, async testConnection(provider, options) { const started = Date.now(); await request(provider, "/models", undefined, options.signal); return { ok: true, latencyMs: Date.now() - started, model: provider.model }; } };
}

function completionFromPayload(payload: any, fallbackModel: string): LlmCompletion { const message = payload.choices?.[0]?.message; if (!message || (!message.content && !message.reasoning_content && !message.reasoning && !message.tool_calls?.length)) throw new LlmAdapterError("model provider returned no assistant message", "protocol", false); const usage = payload.usage ? { promptTokens: payload.usage.prompt_tokens, completionTokens: payload.usage.completion_tokens, totalTokens: payload.usage.total_tokens } : undefined; return { content: message.content ?? "", reasoning: message.reasoning_content ?? message.reasoning ?? "", tool_calls: message.tool_calls ?? [], model: payload.model ?? fallbackModel, ...(usage ? { usage } : {}) }; }

export async function* parseSse(body: ReadableStream<Uint8Array>): AsyncIterable<LlmDelta> { const reader = body.getReader(); const decoder = new TextDecoder(); let buffer = ""; try { while (true) { const part = await reader.read(); if (part.done) break; buffer += decoder.decode(part.value, { stream: true }); const lines = buffer.split(/\r?\n/); buffer = lines.pop() ?? ""; for (const line of lines) { if (!line.startsWith("data:")) continue; const raw = line.slice(5).trim(); if (!raw || raw === "[DONE]") continue; const payload = JSON.parse(raw); const choice = payload.choices?.[0]; const delta = choice?.delta; if (delta) { if (delta.content) yield { content: delta.content, model: payload.model }; if (delta.reasoning_content || delta.reasoning) yield { reasoning: delta.reasoning_content ?? delta.reasoning, model: payload.model }; for (const [index, call] of (delta.tool_calls ?? []).entries()) yield { toolCall: { index, id: call.id, name: call.function?.name, arguments: call.function?.arguments }, model: payload.model }; } if (payload.usage) yield { usage: { promptTokens: payload.usage.prompt_tokens, completionTokens: payload.usage.completion_tokens, totalTokens: payload.usage.total_tokens } }; } } } finally { reader.releaseLock(); } }
